# docker-compose.yml
# Ubica este archivo en la raíz de tu proyecto (junto a vuelosFrontend, vuelosBackend, vuelosIA)

# version: '3.8' # Opcional

services:
  # Servicio de Backend (vuelosBackend)
  backend:
    build:
      context: ./vuelosBackend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./vuelosBackend/anti-script:/app/anti-script
      - /app/anti-script/node_modules
    environment:
      NODE_ENV: development
      IA_API_BASE_URL: http://ia-api:3020/api
    depends_on:
      - ia-api

  # Servicio de Frontend (vuelosFrontend)
  frontend:
    build:
      context: ./vuelosFrontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_IA_API_URL: http://ia-api:3020
        NEXT_PUBLIC_BACKEND_API_URL: http://backend:3030
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - ia-api

  ia-api:
    build:
      context: ./vuelosIA/api-js
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    volumes:
      - ./vuelosIA/api-js:/app/vuelosIA/api-js
      - /app/vuelosIA/api-js/node_modules
    environment:
      NODE_ENV: development
      BACKEND_API_URL: http://backend:3030

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ollama_data:
