version: '3.8'

services:
  backend:
    build:
      context: ./vuelosBackend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: development
      IA_API_BASE_URL: http://ia-api:3020/api
    depends_on:
      - ia-api

  frontend:
    build:
      context: ./vuelosFrontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_IA_API_URL: http://ia-api:3020
      NEXT_PUBLIC_BACKEND_API_URL: http://backend:3030
    depends_on:
      - ia-api
      - backend

  ia-api:
    build:
      context: ./vuelosIA/api-js
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    volumes:
      - ./vuelosIA/api-js:/app/vuelosIA/api-js
      - vuelosia_node_modules:/app/vuelosIA/api-js/node_modules
    environment:
      NODE_ENV: development
      BACKEND_API_URL: http://backend:3030

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ollama_data:
  vuelosia_node_modules:
